# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_name', models.CharField(max_length=255)),
                ('meet_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_distance', models.IntegerField()),
                ('units', models.CharField(choices=[('m', 'm'), ('km', 'km'), ('mi', 'mi')], default='km', max_length=255)),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('seconds', models.DecimalField(decimal_places=2, max_digits=2)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='running_site.Meet')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='running_site.Runner'),
        ),
    ]
