# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='seconds',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
