# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 01:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_site', '0003_auto_20171220_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='number_distance',
            field=models.DecimalField(decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
