# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 01:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_site', '0006_auto_20171221_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
