# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 01:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_site', '0007_auto_20171221_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='minutes',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)]),
        ),
    ]
